services:
  watchild-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /tmp:/tmp
    environment:
      - SPRING_PROFILES_ACTIVE=dev